source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RSEmailFeedback_Example' do
  pod 'RSEmailFeedback', :path => '../'
end

target 'RSEmailFeedback_Tests' do
  pod 'RSEmailFeedback', :path => '../'
end
