source 'https://cdn.cocoapods.org'
platform :ios, '12.0'
use_frameworks!

target 'RSEmailFeedback_Example' do
  pod 'RSEmailFeedback', :path => '../'
end

target 'RSEmailFeedback_Tests' do
  pod 'RSEmailFeedback', :path => '../'
end
