source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RSEmailFeedback_Example', :exclusive => true do
  pod 'RSEmailFeedback', :path => '../'
end

target 'RSEmailFeedback_Tests', :exclusive => true do
  pod 'RSEmailFeedback', :path => '../'

  
end
